version: '3'
services:
  demo:
    build:
         dockerfile: ./Dockerfile
    ports:
      - "3251:3251"
    volumes:
      - .:/app
      - ./alias.json:/home/node/.mcv/alias.json
      - deps:/app/node_modules
    tty: true
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    network_mode: bridge

volumes:
  deps:


